'''memex_dossier.handles.dump shows the username data found in a set of cbor
files generated by memex_dossier/streamcorpus_structured/run.py

.. This software is released under an MIT/X11 open source license.
   Unpublished Work Copyright 2015 Diffeo, Inc.

'''
import cbor
import gzip

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('input', nargs='+')
parser.add_argument('--show-repr', action='store_true')
args = parser.parse_args()

def usernames():
    for path in args.input:
        with gzip.open(path) as fh:
            while True:
                try:
                    rec = cbor.load(fh)
                except EOFError:
                    break

                if 'username' in rec:
                    for username in rec['username']:
                        if not isinstance(username, unicode):
                            username = username.decode('utf8')
                            yield username

                if 'email' in rec:
                    for email in rec['email']:
                        uname = email.split('@')[0]
                        yield uname



for username in usernames():
    if args.show_repr:
        print '%r --> %s' % (username, username)
    else:
        print username
