'''
Web services for active learning search engines
===============================================
This library ships with a command line application, ``memex_dossier.models``,
that runs a web service. It is easy to run::

    memex_dossier.models -c config.yaml

This runs it on ``localhost:8080``. A sample config file looks like:

.. code-block:: yaml

    memex_dossier.store:
      feature_indexes: ['bowNP_sip', 'phone', 'region']

    memex_dossier.models:
      tfidf_path: /path/to/tfidf/model.tfidf

    kvlayer:
      app_name: memex_dossierstack
      namespace: myapp
      storage_type: redis
      storage_addresses: ['localhost:6379']

Where the ``tfidf_path`` corresponds to a TF-IDF model generated by
``gensim``. You can create one with the ``memex_dossier.etl tfidf`` command.
(Note that this is optional!)

Once ``memex_dossier.models`` is running, you can try the
Sorting Desk browser extension for Google Chrome:
https://chrome.google.com/webstore/detail/sorting-desk/ikcaehokdafneaiojndpmfbimilmlnid.
Once the extension is installed, you'll need to go to
its options and configure it to point to ``http://localhost:8080``.

Alternatively, you can follow the steps here to get a simple example
working on a sample data set:
https://github.com/memex_dossier/memex_dossier.models#running-a-simple-example.


Web service endpoints
---------------------
The web service has all of the same endpoints as :mod:`memex_dossier.web`.
A couple of the endpoints are slightly enhanced to take advantage of
``memex_dossier.models`` pairwise learning algorithm and feature extraction.
These enhanced endpoints are :func:`memex_dossier.web.routes.v1_search` and
:func:`memex_dossier.web.routes.v1_fc_put`. The ``v1_search`` endpoint is
enhanced with the addition of the :func:`memex_dossier.models.similar` and
:func:`memex_dossier.models.dissimilar` search engines. Additionally, the
``v1_fc_put`` accepts ``text/html`` content and will generate a feature
collection for you.


How the Sorting Desk browser extension works
--------------------------------------------
SortingDesk needs a ``memex_dossier.models`` web server in order to function
properly. Namely, it uses ``memex_dossier.models`` (and the underlying
Memex_DossierStack) to add/update feature collections, store ground truth
data as "labels," and run pairwise learning algorithms to rank relevant
search results. All of this information is saved to the underlying
database, so it is persistent across all user sessions.

'''
from __future__ import absolute_import, division, print_function

import argparse
import logging

import bottle

import dblogger
from memex_dossier.models.web.config import Config
from memex_dossier.models.web.routes import app as models_app
import memex_dossier.web as web
import kvlayer
import yakonfig


logger = logging.getLogger(__name__)


def get_application():
    config = Config()
    p = argparse.ArgumentParser(description='Run Memex Dossier Stack web services.')
    web.add_cli_arguments(p)
    args = yakonfig.parse_args(p, [dblogger, config, kvlayer, yakonfig])

    bottle.debug(True)
    app = (web.WebBuilder()
           .set_config(config)
           .enable_cors()
           .inject('tfidf', lambda: config.tfidf)
           .inject('google', lambda: config.google)
           .inject('akagraph', lambda: config.akagraph)
           .inject('akagraph_replicas', lambda: config.akagraph_replicas)
           .add_routes(models_app)
           .get_app())
    return args, app


def main():
    args, app = get_application()
    app.run(server='wsgiref', host=args.host, port=args.port,
            debug=args.bottle_debug, reloader=args.reload)


if __name__ == '__main__':
    main()
