#!/usr/bin/env python

# This script creates sample data that can be inserted into dossier.store.
# This data currently powers some of the simplest examples until we get
# more sophisticated test sets.
#
# The results of this script are committed to the repo so that they are
# easily accessible by others. ---AG

import collections
import sys

from dossier.fc import FeatureCollection, FeatureCollectionChunk

fc_data = [
    ('doc1', 'http://en.wikipedia.org/wiki/Chargino', 'Chargino', [
        'In particle physics, the chargino is a hypothetical particle which refers to the mass eigenstates of a charged superpartner, i.e. any new electrically charged fermion (with spin 1/2) predicted by supersymmetry.',
        'The heavier chargino can decay through the neutral Z boson to the lighter chargino.',
    ]),
    ('doc2', 'http://en.wikipedia.org/wiki/Neutralino', 'Neutralino', [
        'In particle physics, the neutralino[1] is a hypothetical particle predicted by supersymmetry.',
        'In R-parity conserving models, the lightest neutralino is stable and all supersymmetric cascade-decays end up decaying into this particle which leaves the detector unseen and its existence can only be inferred by looking for unbalanced momentum in a detector.',
        'The mass splittings between the different neutralinos will dictate which patterns of decays are allowed.',
        'As a heavy, stable particle, the lightest neutralino is an excellent candidate to comprise the universe\'s cold dark matter.',
    ]),
    ('doc3', 'http://en.wikipedia.org/wiki/Photino', 'Photino', [
        'A photino is a hypothetical subatomic particle, the fermion WIMP superpartner of the photon predicted by supersymmetry.',
        'Photinos have a lepton number 0, baryon number 0, and spin 1/2.',
    ]),
    ('doc4', 'http://en.wikipedia.org/wiki/Higgsino', 'Higgsino', [
        'In particle physics, a Higgsino, symbol H is the hypothetical superpartner of the Higgs boson, as predicted by supersymmetry.',
        'The Higgsino is a Dirac fermion and that is a weak isodoublet with hypercharge half under the Standard Model gauge symmetries.',
        'If dark matter is composed only of Higgsinos then the Higgsino mass is 1.1 TeV.',
        'After electroweak symmetry breaking the Higgsino becomes a pair of neutral Majorana fermions called neutralinos and a charged Dirac fermion called a chargino (plus and minus).',
    ]),
    ('doc5', 'http://en.wikipedia.org/wiki/Gluino', 'Gluino', [
        'A gluino (symbol g) is the hypothetical supersymmetric partner of a gluon.',
        'Gluinos have a lepton number 0, baryon number 0, and spin 1/2.',
        'However if gluinos are lighter than squarks, 3-body decay of a gluino to a neutralino and a quark antiquark pair is kinematically accessible through an off-shell squark.',
    ]),
    ('doc6', 'http://en.wikipedia.org/wiki/Gravitino', 'Gravitino', [
        'The gravitino (G) is the gauge fermion supersymmetric partner of the graviton, as predicted by theories combining general relativity and supersymmetry; i.e. supergravity theories.',
        'If the gravitino indeed has a mass of the order of TeV, then it creates a problem in the standard model of cosmology, at least naively.',
    ]),
]


def bow(s, min_length=5):
    d = collections.defaultdict(int)
    for word in s.split():
        if len(word) >= min_length:
            d[word] += 1
    return d


def convert_data_to_fcs(datum):
    prefix_id, url, name, texts = datum
    fcs = []
    for i, text in enumerate(texts, 1):
        fcs.append(FeatureCollection({
            u'content_id': ('%s%d' % (prefix_id, i)).decode('utf-8'),
            u'NAME': {name.decode('utf-8'): 1},
            u'abs_url': {url: 1},
            u'sentences': {text: 1},
            u'keywords': bow(text),
        }))
    return fcs


if __name__ == '__main__':
    chunk = FeatureCollectionChunk(file_obj=sys.stdout, mode='wb')
    for datum in fc_data:
        for fc in convert_data_to_fcs(datum):
            chunk.add(fc)
    chunk.flush()
